// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"official/UniqueDataLoader","status":false,"description":"Unique Data Loading Plugin","parameters":{"GlobalVariableName":"$dataUniques","UniqueDataList":"[]"}},
{"name":"launch/PluginBaseFunction","status":true,"description":"Plugin Common Functions","parameters":{}},
{"name":"scripts/RemoveBars","status":true,"description":"","parameters":{}}
];
